### ISSUE TITLE
Is there public Helm repository URL?

### ISSUE THREAD

**Issue by ismailbaskin** [orangesys/charts#1]

**Comment by gavinzhou** [comment]
yes ,this is public helm repo 
run it in my live

create  repo with google cloud storage use this script
https://github.com/orangesys/charts/tree/master/scripts

**Comment by ismailbaskin** [comment]
Thank you, I missed that scripts. I've installed orange/kong but there is problem about image pull.

> Failed to pull image "asia.gcr.io/saas-orangesys-io/alpine-job:0.1.6": Error: Status 403 trying to pull repository saas-orangesys-io/alpine-job: "Unable to access the repository: saas-orangesys-io/alpine-job; please verify that it exists and you have permission to access it."

**Comment by gavinzhou** [comment]
can get docker image in my docker hub 
https://hub.docker.com/u/orangesys/dashboard/

```
 docker pull orangesys/alpine-job:0.1.6
 docker tag orangesys/alpine-job:0.1.6 asia.gcr.io/<YOUR PROJECT>/alpine-job:0.1.6
```

OR

change helm template
```
 asia.gcr.io/saas-orangesys-io/alpine-job:0.1.6 -> orangesys/alpine-job:0.1.6
```
